export const FETCH_WORKOUTS = 'FETCH_WORKOUTS';
export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS';
export const ADD_WORKOUT = 'ADD_WORKOUT';
export const UPDATE_CURRENTWORKOUT = 'UPDATE_CURRENTWORKOUT';
